#!/bin/bash
set -euo pipefail

# QuickJS WASI Reactor Update Script
# Downloads the reactor variant from quickjs-ng/quickjs releases

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="quickjs-ng/quickjs"
ASSET_NAME="qjs-wasi-reactor.wasm"
OUTPUT_NAME="qjs-wasi.wasm"

# Use tag from first argument, or find the latest release
TAG="${1:-}"
if [ -z "$TAG" ]; then
    echo "Fetching latest release from $REPO..."
    TAG=$(gh release view --repo "$REPO" --json tagName --jq '.tagName')
fi

if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
    echo "Error: Could not determine release tag"
    exit 1
fi

echo "Release: $TAG"
echo "Downloading $ASSET_NAME..."

# Download the WASM file
gh release download "$TAG" --repo "$REPO" --pattern "$ASSET_NAME" --output "$SCRIPT_DIR/$OUTPUT_NAME" --clobber

echo "Downloaded $OUTPUT_NAME ($(wc -c < "$SCRIPT_DIR/$OUTPUT_NAME" | tr -d ' ') bytes)"

# Generate version info
DOWNLOAD_URL="https://github.com/$REPO/releases/download/$TAG/$ASSET_NAME"
echo "Generating src/version.ts..."
cat > "$SCRIPT_DIR/src/version.ts" << EOF
// Auto-generated by update-quickjs.bash
// Do not edit manually

/** QuickJS-NG version string */
export const VERSION = '$TAG'

/** Download URL for the WASM binary */
export const DOWNLOAD_URL = '$DOWNLOAD_URL'
EOF

echo "Updated src/version.ts"
echo ""
echo "Update complete!"
