#!/bin/bash
set -eo pipefail

# This script updates the QuickJS WASM binary from the latest release.
# It downloads the reactor variant from paralin/quickjs releases.

REPO="paralin/quickjs"
ASSET_NAME="qjs-wasi-reactor.wasm"
OUTPUT_NAME="qjs-wasi.wasm"

echo "Fetching latest release from $REPO..."

# Get the latest release info
RELEASE_INFO=$(curl -s "https://api.github.com/repos/$REPO/releases/latest")

# Extract the tag name and download URL
TAG=$(echo "$RELEASE_INFO" | grep -o '"tag_name": "[^"]*"' | cut -d'"' -f4)
DOWNLOAD_URL=$(echo "$RELEASE_INFO" | grep -o "\"browser_download_url\": \"[^\"]*$ASSET_NAME\"" | cut -d'"' -f4)

if [ -z "$TAG" ] || [ -z "$DOWNLOAD_URL" ]; then
    echo "Error: Could not find release or asset"
    exit 1
fi

echo "Found release: $TAG"
echo "Downloading $ASSET_NAME..."

# Download the WASM file
curl -L -o "$OUTPUT_NAME" "$DOWNLOAD_URL"

echo "Downloaded $OUTPUT_NAME ($(wc -c < "$OUTPUT_NAME") bytes)"

# Generate version info
cat > src/version.ts << EOF
// Auto-generated by update-quickjs.bash
// Do not edit manually

/** QuickJS-NG version string */
export const VERSION = '$TAG'

/** Download URL for the WASM binary */
export const DOWNLOAD_URL = '$DOWNLOAD_URL'
EOF

echo "Updated src/version.ts"
echo "Done!"
