// Auto-generated by update-quickjs.bash
// Do not edit manually

/** QuickJS-NG version string */
export const VERSION = 'v0.12.1'

/** Download URL for the WASM binary */
export const DOWNLOAD_URL = 'https://github.com/quickjs-ng/quickjs/releases/download/v0.12.1/qjs-wasi-reactor.wasm'
